### ISSUE TITLE
The following StateError was thrown building: Bad state: field does not exist within the DocumentSnapshotPlatform

### ISSUE THREAD

**Issue by DanOs29-D** [MahmoudHesham099/Flutter-Twitter-Clone-Firebase#1]
Hello..Am new to flutter I was trying run the repository on android studio while debugging I got the error.How do I fix it??

Bad state: cannot get a field on a DocumentSnapshotPlatform which does not exist

The relevant error-causing widget was: 
  FutureBuilder<DocumentSnapshot> file:///C:/Users/NM/Desktop/Repositories/memo/lib/screens/ProfileScreen.dart:142:15
When the exception was thrown, this was the stack: 
#0      DocumentSnapshotPlatform.get (package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart:73:7)
#1      DocumentSnapshot.get (package:cloud_firestore/src/document_snapshot.dart:45:43)
#2      DocumentSnapshot.[] (package:cloud_firestore/src/document_snapshot.dart:52:41)
#3      new UserModel.fromDoc (package:memo/Models/UserModel.dart:24:16)
#4      _ProfileScreenState.build.<anonymous closure> (package:memo/screens/ProfileScreen.dart:152:45)

**Comment by MahmoudHesham099** [comment]
Try Changing it to doc.data() ...except for doc.id
or
This issue can happen by passing wrong attribute name that doesn't exist in the document

**Comment by DanOs29-D** [comment]
@MahmoudHesham099 .I got an error that states. 
The method '[]' was called on null.
Receiver: null
Tried calling: []("name")


How do I solve  it?
The code to which the error is from is this.
factory UserModel.fromDoc(DocumentSnapshot doc) {
  return UserModel(
    id: doc.id,
    name: doc.data()['name'],
    email: doc.data()['email'],
    profilePicture: doc.data()['profilePicture'],
    bio: doc.data()['bio'],
    coverImage: doc.data()['coverImage'],

**Comment by DanOs29-D** [comment]
I saw that @jschnip has tried to solve the issue but am having difficult making changes in terms of calling.
He did it like this https://github.com/FirebaseExtended/flutterfire/issues/3826#issuecomment-715591362
